squid:
    build: squid/.
    environment:
        - "DISK_CACHE_SIZE=5000"
        - "MAX_CACHE_OBJECT=1000"
        # - "SQUID_DIRECTIVES_ONLY=true"
        # - "SQUID_DIRECTIVES='refresh_pattern . 0 0 1 refresh-ims'"
    ports:
        - "3129:3129"
    ## Uncomment and update /path/to/cache
    # volumes:
    #   - /path/to/cache:/var/cache/squid3

